#!/bin/sh
set -e

# Project info
PROJECTNAME="xmlm"
VERSION="1.0.2"
COPYRIGHTYEAR="2007-2009"
SHORTDESCRIPTION="Streaming XML input\/output for OCaml"
EMAIL="daniel.buenzl i\\\@erratique.ch"

INSTALLDIR=${INSTALLDIR:="`ocamlc -where`/$PROJECTNAME"}
DOCDIR=${DOCDIR:="doc"}
F=${F:="_build/src/$PROJECTNAME"}

# Caml tools
OCAMLDOC=${OCAMLDOC:="ocamldoc"}
OCAMLBUILD=${OCAMLBUILD:="ocamlbuild"}
BUILDFLAGS=${BUILDFLAGS:="-classic-display"}

# Misc tools
CP=${CP:="cp"}
RM=${RM:="rm"}
MKDIR=${MKDIR:="mkdir"}

ocb () { $OCAMLBUILD $BUILDFLAGS $* ; }

action () 
{
  case $1 in
    module-byte)
      ocb $PROJECTNAME.cmo ;;
    module-native) 
      ocb $PROJECTNAME.cmx ;;
    module-plugin) 
      ocb $PROJECTNAME.cmxs ;;
    module)
      action module-byte
      action module-native ;;
    doc)
      ocb $PROJECTNAME.cmi
      $OCAMLDOC -html -I src -colorize-code -d $DOCDIR src/$PROJECTNAME.mli ;;
    distrib) distrib ;;
    install-byte)
      action module-byte
      $MKDIR -p $INSTALLDIR
      $CP $F.ml $F.mli $F.cmi $F.cmo src/META $INSTALLDIR ;;
    install)
      action install-byte
      action module-native
      $CP $F.cmx $F.o $INSTALLDIR ;;
    install-plugin)
      action install
      action module-plugin
      $CP $F.cmxs $INSTALLDIR ;;
    clean) 
      ocb -clean ;;
    clean-all) 
      action clean
      $RM -f $DOCDIR/*.html ;;
    *) 
      ocb $1;;
  esac;
} 

distrib ()
{
  CD=${CD:="cd"}
  FIND=${FIND:="find"}
  GREP=${GREP:="grep"}
  TAR=${TAR:="tar"}

  DIRNAME=$PROJECTNAME-$VERSION
  ROOTDIR=/tmp/$DIRNAME
  $RM -rf $ROOTDIR
  $MKDIR -p $ROOTDIR
  $CP -r . $ROOTDIR
  $CD $ROOTDIR
  action clean-all

  $RM -rf _darcs
  $RM -f TODO
  $FIND $ROOTDIR \
    \( -name "*~" -o -name ".DS_Store" -o -name ".gdb_history" \) \
    -exec $RM {} ';'
  for file in `$FIND $ROOTDIR -type f -print`; do
    sed -i "s/1.0.2/$VERSION/; \
            s/2007-2009/$COPYRIGHTYEAR/; \
            s/Streaming XML input/output for OCaml/$SHORTDESCRIPTION/; \
            s/daniel.buenzl i\@erratique.ch/$EMAIL/;" \
	$file
  done

  action module
  action xmltrip.native
  action examples.cmo
  action doc
  action clean

  $CD ..
  $TAR -cvjf $DIRNAME.tbz $DIRNAME
  $RM -r $DIRNAME
}

if [ $# -eq 0 ]; then action module ; else
  while [ $# -gt 0 ]; do action $1; shift ; done
fi


