let all_tests = [
  Ucsc_genome_browser.tests;
  Lines.tests;
  Bgzf.tests;
  Bam.tests;
  Roman_num.tests;
  Table.tests;
  Fasta.tests;
  Interval_tree.tests;
  Phred_score.tests;
  Pwm.tests;
  Bin_pred.tests;
  Bed.tests;
  Wig.tests;
  Gff.tests;
  Track.tests;
  Sam.tests;
  Biocaml_test_zip.tests;
  Vcf.tests;
  RSet.tests;
]
